#/docs/_config.yml
# 프로젝트 사이트 필수 설정: url/baseurl 정확히. (빌드 시 테마 자산 경로 문제 방지)
title: "내 프로젝트"
description: "Jekyll + just-the-docs Project Site"
url: "https://kikinim.github.io"     # ← 본인 GitHub ID로
baseurl: "/ssrepo"                    # ← 저장소 이름로 (예: /just-the-docs 가 아니라 /myrepo)

# just-the-docs 원격 테마 사용 (fork 불필요)
remote_theme: just-the-docs/just-the-docs

# 검색/보조 링크 등 옵션
search_enabled: true
aux_links:
  "GitHub Repo":
    - "https://github.com/kikinim/ssrepo"   # ← 본인 repo 링크

# 플러그인 (remote_theme 동작)
plugins:
  - jekyll-remote-theme

# 마크다운/수식
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# 네비게이션 깊이/사이드바 폭(선택)
just_the_docs:
  nav_sort: case_insensitive
  # 추가 자잘 옵션 필요시 여기 확장

# 사용자 CSS 추가(선택)
# 아래 경로의 CSS를 자동 포함하려면 includes/head_custom.html에서 링크함.
