#/docs/_config.yml
# Jekyll 전역 설정 (프로젝트 사이트용). YAML은 #만 주석으로 허용됨.
title: "내 프로젝트"
description: "Jekyll + just-the-docs on GitHub Pages"
url: "https://kikinim.github.io"        # 본인 GitHub ID로 맞음
baseurl: "/just-the-docs"               # 저장소 이름(예: just-the-docs)로 변경

# just-the-docs 테마를 원격으로 사용 (fork 불필요)
remote_theme: just-the-docs/just-the-docs

# 옵션들
search_enabled: true
aux_links:
  "GitHub Repo":
    - "https://github.com/kikinim/just-the-docs"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
